<?php $this->partial('shared/header'); ?>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    Here you find all test result of all required server configuration.
                    Please make sure all test is pass, or fix it if it's not yet.
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="page-header">
                <h3>Server Status</h3>
                
            </div>
            
            <table class="table table-hover">
                <thead><tr><th>Name</th><th>Result</th><th>Info</th></tr></thead>
                <tbody>
                    <?php foreach($tests as $row): ?>
                    <tr>
                        <td><?= $row['desc'] ?></td>
                        <td>
                            <?php if($row['success']): ?>
                            <span class="label label-success">Success</span>
                            <?php else: ?>
                            <span class="label label-danger">Fail</span>
                            <?php endif; ?>
                        </td>
                        <td><?= $row['info'] ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php $this->partial('shared/footer'); ?>